#!/bin/bash
SRC="http://github.com/ezdiy/luagit.git"
BASE=~/dev/.luagit
REPO=$BASE/repo
LIB=$BASE/lib
TMP=/tmp/$$/
CPPFLAGS='-I/usr/include/lua5.1 -I.'
CFLAGS='-O2 -I/usr/include/lua5.1 -I.'
mkdir -p $TMP
if [ ! -d $BASE ]; then
	git clone $SRC $BASE
fi
cd $BASE
mkdir -p $REPO

function go()
{
#	echo "$*"
	$*
}

function do_install()
{
	if [ -z "$1" ]; then
		echo -n "Really install all `echo $BASE/spec/*|wc -w` packages? [y/N]"
		read -n 1 resp
		if [ "$resp" != "y" ]; then
			return
		fi
		for n in $BASE/spec/*; do
			do_install `basename $n`
		done
		return
	fi
	if [ -f "$TMP$1" ]; then
		return
	fi
	nn="$1"
	echo "Installing '$1'..."
	function do_configure()
	{
		wd=`pwd`
		cd $BASE/repo/$nn
		if [ ! -f configure ]; then
			./bootstrap
		fi
		if [ ! -f config.h ]; then
			# XXX todo, what about others than debian/ubuntu?
			CPPFLAGS='-I/usr/include/lua5.1' ./configure --libdir=/usr/local/lib/lua/5.1 --datadir=/usr/local/share/lua/5.1 --with-lua-suffix=5.1
		fi
		cd $wd
	}
	function do_make()
	{
		wd=`pwd`
		cd $wd
	}
	function import()
	{
		file="$2"
		ext=${file##*.} 
		fl=`echo "$1" | sed -e 's#\.#/#g'`
		if [ $ext == "lua" ]; then
			mkdir -p `dirname "$LIB/$fl"`
			cp -f "$2" "$LIB/$fl.lua"
		elif [ "$ext" == "so" ]; then
			mkdir -p `dirname "$LIB/$fl"`
			cp -f "$2" "$LIB/$fl.$ext"
		elif [ "$ext" == "c" ]; then
			shift
			all=""
			for fn in $*; do
				fo="${fn%.*}.o"
				go gcc -fPIC -O2 $CFLAGS -c "$fn" -o "$fo"
				all="$fo $all"
			done
			mkdir -p `dirname "$LIB/$fl"`
			go gcc -shared -fpic $all -o "$LIB/$fl.so" $LDFLAGS
		fi
	}
	function depend()
	{
		TODO="$1 $TODO"
	}
	cd $REPO/$1
	. $BASE/spec/$1 2> /dev/null
	touch $TMP$1
	for n in $TODO; do
		if [ -f $TMP$n ]; then
			continue
		fi
		do_install $n
	done
#2>/dev/null
}

function do_update()
{
	INPUT=""
	TODO=""
	function source()
	{
		DIR=`basename $INPUT`
		if [ ! -d "$REPO/$DIR" ]; then
			(git clone $1 $REPO/$DIR > /dev/null; echo -n "#")&
		else
			(cd $REPO/$DIR; git pull > /dev/null; echo -n "#")&
		fi
	}

	echo "Updating packages"
	echo -n "["
	for n in $BASE/spec/*; do echo -n .; done
	echo -ne "]\r["

	for n in $BASE/spec/*; do
		INPUT=$n
		. $n 2> /dev/null
	done
	wait
	echo "] OK!"
}

case $1 in
	"update")
		echo -n "Updating LuaGIT.."
		cd $BASE && git pull
		do_update
		;;
	"install")
		do_install $2
		rm -rf $TMP
		;;
	*)
		echo "Unknown command '$1'"
		exit 1
		;;
esac

