#!/bin/sh
REPO="http://github.com/ezdiy/luagit.git"
BASE=~/.luagit
LUAGIT=$BASE/luagit
mkdir -p $BASE
cd $BASE
if [ ! -d luagit ]; then
	git clone $REPO
fi
case $1 in
	"update")
		cd $LUAGIT && git pull
		;;
	*)
		echo "Unknown command '$1'"
		exit 1
		;;
esac

